# Generated by Django 4.2 on 2023-04-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_globalconfig_topic_course_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hook',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
