# Generated by Django 4.2 on 2023-04-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_course_hook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='requirements',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='who_this_course_is_for',
            field=models.TextField(null=True),
        ),
    ]
