# Generated by Django 4.2 on 2023-04-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_bundleregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='discount_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='course',
            name='discount_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
