# Generated by Django 4.2 on 2023-04-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_salemessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='course',
        ),
        migrations.AddField(
            model_name='contact',
            name='description',
            field=models.TextField(max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
